name: NaleumFramework
version: '1.1.2'
main: com.github.NaleumFramework
api-version: '1.20'
commands:
  nlreload:
    description: reload NaleumFramework
    usage: /nlreload

softdepend: ["PlaceholderAPI"]